### ISSUE TITLE
No support for Teensy 3.1

### ISSUE THREAD

**Issue by twinotter** [cpldcpu/light_ws2812#16]
I'm looking for a solution that will work on the Teensy 3.1. The Teensy uses an MX20DX256 which is ARM based and compiles in the Arduino IDE. It looks like the Arduino support is primary intended for Atmel chips. The ARM support that is being tested right now doesn't compile under the Arduino. The following error is given:

light_ws2812.cpp: In member function 'void WS2812::ws2812_sendarray_mask(uint8_t*, uint16_t, uint8_t, uint8_t*, uint8_t*)':
light_ws2812.cpp:152: error: impossible constraint in 'asm'

As far as I can tell, the port definitions that are set using digitalPinToBitMAsk, etc. are not defined in the Teensy because of different hardware in the ARM chip. I'm basing this on comments here: http://forum.pjrc.com/threads/26225-problem-bit-banging-using-digitalPinToBitMask-et-al

This likely also means the Arduino Due won't work, yet.
